server:
  port: 8096

spring:
  application:
    name: P2P-SERVICE

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: false
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

logging:
  level:
    root: INFO
    org.springframework.web.socket: DEBUG # Live-tracks connection/disconnection handshakes
    com.SHADOW.P2P_SERVICE: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} : %msg%n"